### ISSUE TITLE
Incompatible with Procedural Parts

### ISSUE THREAD

**Issue by Lenniepen** [icedown/KSP-ProbeControlRoom#1]
Hi,
First of all, thank you very much for maintaining this mod!
This is my first GitHub-issue, so I'm not sure I do it correctly.

Issue:
Ksp version: 1.2.1
When using any part of the Procedural Parts mod (version 1.2.7) in a unmanned craft, ProbeControlRoom doesn't work:
- the ProbeControlRoom-icon does not appear in the Toolbar.
- right clicking on the probe shows the IVA ProbeControl-button, but clicking on it doesn't do anything. 0 - - using the 'C' button to enter IVA doesn't work.

Thanks in advance,
Lennart

**Comment by icedown** [comment]
Verified this.  Working on it now. In  the future, be sure to post your output_log.txt as well.

**Comment by icedown** [comment]
Found and fixed, pushing out new update now.
