### ISSUE TITLE
Small Bug with toolbar

### ISSUE THREAD

**Issue by Mecripp** [icedown/KSP-ProbeControlRoom#3]
There is a small bug with last update the toolbar png got moved to a Icons folder and toolbar just shows a purple square but the ksp stock toolbar show it right, I copied the 2 png's to just the ProbeControlRoom folder and reloaded and toolbar shows up right now if, I delete the icons folder then the stock toolbar is a white square.

**Comment by icedown** [comment]
I forgot to change the location in the toolbar class.  Fixed. This will be part of the next update.
